# Generated by Django 3.2 on 2021-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BashBuckets', '0002_apptokens_userbuckets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppTokens',
            new_name='AppToken',
        ),
    ]
