# Generated by Django 3.2 on 2021-06-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BashBuckets', '0003_rename_apptokens_apptoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBuckets',
            new_name='UserBucket',
        ),
    ]
