# Generated by Django 3.2 on 2021-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BashBuckets', '0005_user_usage_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usage_limit',
            field=models.IntegerField(default=1024, verbose_name='Usage Limit (MB)'),
        ),
    ]
