# Generated by Django 3.2 on 2021-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BashBuckets', '0007_remove_bucket_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
