# Generated by Django 3.2 on 2021-06-07 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BashBuckets', '0008_alter_bucket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BashBuckets.bucket')),
            ],
        ),
    ]
